# Generated by Django 3.2.16 on 2022-12-08 12:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20221206_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='allowed_domains',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), blank=True, default=list, help_text='The domains must be added with comma separator e.g `firstone.com,secondone.com`. Do not include `@`!', size=None),
        ),
    ]
