# Generated by Django 3.2.16 on 2022-12-12 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_organization_allowed_domains'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='is_shared',
        ),
    ]
