# Generated by Django 3.1.4 on 2021-03-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_survey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyattribute',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Survey Attribute'},
        ),
        migrations.AlterModelOptions(
            name='surveycategory',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Survey Category', 'verbose_name_plural': 'Survey Categories'},
        ),
        migrations.AlterModelOptions(
            name='surveymode',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Survey Mode'},
        ),
        migrations.AlterModelOptions(
            name='surveytype',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Survey Type'},
        ),
        migrations.AddField(
            model_name='surveyattribute',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveycategory',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveymode',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveytype',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
