# Generated by Django 3.1.4 on 2021-03-05 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20210305_1043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Survey',
        ),
    ]
