# Generated by Django 3.1.4 on 2021-04-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveytype',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='survey_types', to='surveys.SurveyAttribute'),
        ),
    ]
