# Generated by Django 3.1.4 on 2021-04-28 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_surveytype_attributes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyattribute',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Survey Context', 'verbose_name_plural': 'Survey Context'},
        ),
    ]
