# Generated by Django 3.1.4 on 2021-04-29 06:38

import core.validators
import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0007_auto_20210428_0755"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyattribute",
            name="name",
            field=django.contrib.postgres.fields.citext.CICharField(
                max_length=255,
                unique=True,
                validators=[core.validators.validate_wfp_name],
                verbose_name="WFP Name",
            ),
        ),
        migrations.AlterField(
            model_name="surveycategory",
            name="name",
            field=django.contrib.postgres.fields.citext.CICharField(
                max_length=255,
                unique=True,
                validators=[core.validators.validate_wfp_name],
                verbose_name="WFP Name",
            ),
        ),
        migrations.AlterField(
            model_name="surveymode",
            name="name",
            field=django.contrib.postgres.fields.citext.CICharField(
                max_length=255,
                unique=True,
                validators=[core.validators.validate_wfp_name],
                verbose_name="WFP Name",
            ),
        ),
        migrations.AlterField(
            model_name="surveytype",
            name="name",
            field=django.contrib.postgres.fields.citext.CICharField(
                max_length=255,
                unique=True,
                validators=[core.validators.validate_wfp_name],
                verbose_name="WFP Name",
            ),
        ),
    ]
