# Generated by Django 3.2.14 on 2022-08-07 10:25

import core.validators
import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0009_auto_20220710_1746"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyattribute",
            name="name",
            field=django.contrib.postgres.fields.citext.CICharField(
                max_length=255,
                unique=True,
                validators=[core.validators.validate_wfp_name],
                verbose_name="WFP Name",
            ),
        ),
        migrations.AlterField(
            model_name="surveycategory",
            name="name",
            field=django.contrib.postgres.fields.citext.CICharField(
                max_length=255,
                unique=True,
                validators=[core.validators.validate_wfp_name],
                verbose_name="WFP Name",
            ),
        ),
        migrations.AlterField(
            model_name="surveymode",
            name="name",
            field=django.contrib.postgres.fields.citext.CICharField(
                max_length=255,
                unique=True,
                validators=[core.validators.validate_wfp_name],
                verbose_name="WFP Name",
            ),
        ),
        migrations.AlterField(
            model_name="surveytype",
            name="name",
            field=django.contrib.postgres.fields.citext.CICharField(
                max_length=255,
                unique=True,
                validators=[core.validators.validate_wfp_name],
                verbose_name="WFP Name",
            ),
        ),
    ]
