# Generated by Django 3.2.16 on 2023-01-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_remove_organization_is_shared'),
        ('surveys', '0010_auto_20220807_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyattribute',
            name='organizations',
            field=models.ManyToManyField(to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='surveycategory',
            name='organizations',
            field=models.ManyToManyField(to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='surveymode',
            name='organizations',
            field=models.ManyToManyField(to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='surveytype',
            name='organizations',
            field=models.ManyToManyField(to='organization.Organization'),
        ),
    ]
