# Generated by Django 3.2.16 on 2023-01-11 09:38
from django.conf import settings
from django.db import migrations


def attach_default_organizations(app, schema_editor):
    SurveyCategory = app.get_model('surveys', "SurveyCategory")
    SurveyType = app.get_model('surveys', 'SurveyType')
    SurveyMode = app.get_model('surveys', 'SurveyMode')
    SurveyAttribute = app.get_model('surveys', 'SurveyAttribute')
    Organization = app.get_model('organization', 'Organization')

    default_organization = Organization.objects.get(name=settings.INITIAL_ORGANIZATION)
    for survey_category in SurveyCategory.objects.all().iterator():
        survey_category.organizations.add(default_organization)
    for survey_type in SurveyType.objects.all().iterator():
        survey_type.organizations.add(default_organization)
    for survey_mode in SurveyMode.objects.all().iterator():
        survey_mode.organizations.add(default_organization)
    for survey_attribute in SurveyAttribute.objects.all().iterator():
        survey_attribute.organizations.add(default_organization)


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_auto_20230111_0926'),
    ]

    operations = [
        migrations.RunPython(attach_default_organizations, reverse_code=migrations.RunPython.noop)
    ]
