# Generated by Django 3.2.18 on 2023-05-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0012_auto_20230111_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyattributetranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('ar', 'Arabic'), ('zh-cn', 'Chinese'), ('ru', 'Russian'), ('pt', 'Portuguese')], max_length=255),
        ),
        migrations.AlterField(
            model_name='surveycategorytranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('ar', 'Arabic'), ('zh-cn', 'Chinese'), ('ru', 'Russian'), ('pt', 'Portuguese')], max_length=255),
        ),
        migrations.AlterField(
            model_name='surveymodetranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('ar', 'Arabic'), ('zh-cn', 'Chinese'), ('ru', 'Russian'), ('pt', 'Portuguese')], max_length=255),
        ),
        migrations.AlterField(
            model_name='surveytypetranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('ar', 'Arabic'), ('zh-cn', 'Chinese'), ('ru', 'Russian'), ('pt', 'Portuguese')], max_length=255),
        ),
    ]
