# Generated by Django 3.2.18 on 2023-06-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0013_auto_20230518_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveytype',
            name='password_protected',
            field=models.BooleanField(default=False),
        ),
    ]
