# Generated by Django 3.2.18 on 2023-06-09 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_add_global_admin_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modules', '0020_auto_20230518_1056'),
        ('questions', '0036_auto_20230518_1056'),
        ('surveys', '0014_surveytype_password_protected'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('attributes', models.ManyToManyField(blank=True, related_name='saved_surveys', to='surveys.SurveyAttribute')),
                ('indicators', models.ManyToManyField(blank=True, related_name='saved_surveys', to='modules.Indicator')),
                ('organizations', models.ManyToManyField(blank=True, related_name='saved_surveys', to='organization.Organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('submodules', models.ManyToManyField(related_name='saved_surveys', to='modules.Submodule')),
                ('subquestions', models.ManyToManyField(blank=True, related_name='saved_surveys', to='questions.SubQuestion')),
                ('survey_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_surveys', to='surveys.surveycategory')),
                ('survey_mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_surveys', to='surveys.surveymode')),
                ('survey_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_surveys', to='surveys.surveytype')),
            ],
            options={
                'ordering': ['-date_created', '-date_updated'],
                'abstract': False,
            },
        ),
    ]
