# Generated by Django 3.2.19 on 2023-06-30 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0020_auto_20230518_1056'),
        ('questions', '0036_auto_20230518_1056'),
        ('surveys', '0015_savedsurvey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedsurvey',
            name='subquestions',
        ),
        migrations.CreateModel(
            name='SubQuestionSubmodule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('saved_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subquestions_submodules', to='surveys.savedsurvey')),
                ('submodule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subquestions', to='modules.submodule')),
                ('subquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submodules', to='questions.subquestion')),
            ],
            options={
                'ordering': ['-date_created', '-date_updated'],
                'abstract': False,
            },
        ),
    ]
