# Generated by Django 3.2.19 on 2023-07-05 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0016_auto_20230630_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subquestionsubmodule',
            name='saved_survey',
        ),
        migrations.RemoveField(
            model_name='subquestionsubmodule',
            name='submodule',
        ),
        migrations.RemoveField(
            model_name='subquestionsubmodule',
            name='subquestion',
        ),
        migrations.DeleteModel(
            name='SavedSurvey',
        ),
        migrations.DeleteModel(
            name='SubQuestionSubmodule',
        ),
    ]
