# Generated by Django 3.2.19 on 2023-07-06 13:12

import core.validators
import django.contrib.postgres.fields.citext
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0017_auto_20230705_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyattribute',
            name='label',
            field=models.TextField(verbose_name='Label (en)'),
        ),
        migrations.AlterField(
            model_name='surveyattribute',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=255, unique=True, validators=[core.validators.validate_name], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='surveycategory',
            name='label',
            field=models.TextField(verbose_name='Label (en)'),
        ),
        migrations.AlterField(
            model_name='surveycategory',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=255, unique=True, validators=[core.validators.validate_name], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='surveymode',
            name='label',
            field=models.TextField(verbose_name='Label (en)'),
        ),
        migrations.AlterField(
            model_name='surveymode',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=255, unique=True, validators=[core.validators.validate_name], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='surveytype',
            name='label',
            field=models.TextField(verbose_name='Label (en)'),
        ),
        migrations.AlterField(
            model_name='surveytype',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=255, unique=True, validators=[core.validators.validate_name], verbose_name='Name'),
        ),
    ]
