# Generated by Django 4.2.23 on 2025-10-21 12:47

from django.db import migrations, models


def add_all_attributes_to_modes(apps, schema_editor):
    SurveyMode = apps.get_model("surveys", "SurveyMode")
    SurveyAttribute = apps.get_model("surveys", "SurveyAttribute")

    attributes = list(SurveyAttribute.objects.all())
    if not attributes:
        return

    for mode in SurveyMode.objects.all():
        mode.attributes.add(*attributes)


def remove_attributes_from_modes(apps, schema_editor):
    SurveyMode = apps.get_model("surveys", "SurveyMode")
    for mode in SurveyMode.objects.all():
        mode.attributes.clear()


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0019_alter_surveyattribute_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveymode",
            name="attributes",
            field=models.ManyToManyField(
                blank=True, related_name="survey_modes", to="surveys.surveyattribute"
            ),
        ),
        migrations.RunPython(add_all_attributes_to_modes, remove_attributes_from_modes),
    ]
