# Generated by Django 3.1.4 on 2021-02-05 13:21

from django.db import migrations


def create_admins_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.create(name="Admins")

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_admins_group, reverse_code=migrations.RunPython.noop),
    ]
