# Generated by Django 3.1.4 on 2021-03-03 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userapikey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userapikey',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='userapikey',
            unique_together={('user', 'site')},
        ),
    ]
