# Generated by Django 3.1.4 on 2021-03-05 11:11

from django.db import migrations


def create_read_only_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.create(name="Read Only")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210303_1911'),
    ]

    operations = [
        migrations.RunPython(create_read_only_group, reverse_code=migrations.RunPython.noop),
    ]
