# Generated by Django 3.1.4 on 2021-03-26 11:47

from django.db import migrations


def create_bulk_upload_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.create(name="Bulk Upload")




class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210305_1111'),
    ]

    operations = [
        migrations.RunPython(create_bulk_upload_group, reverse_code=migrations.RunPython.noop),
    ]
