# Generated by Django 3.1.4 on 2021-04-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210326_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapikey',
            name='site',
            field=models.CharField(choices=[('MODA_DEV', 'MODA DEV'), ('MODA', 'MODA')], max_length=255),
        ),
    ]
