# Generated by Django 3.1.4 on 2021-04-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210402_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapikey',
            name='site',
            field=models.CharField(choices=[('MODA_DEV', 'MODA DEV'), ('MODA', 'MODA'), ('KOBO', 'KOBO')], max_length=255),
        ),
    ]
