# Generated by Django 3.1.4 on 2021-04-19 06:21

from django.db import migrations


def create_notifications_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.create(name="Notifications")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210406_0657'),
    ]

    operations = [
        migrations.RunPython(create_notifications_group, reverse_code=migrations.RunPython.noop),
    ]
