# Generated by Django 3.1.4 on 2021-04-28 16:28

from django.db import migrations


def create_change_requests_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.create(name="Change Requests")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210419_0621'),
    ]

    operations = [
        migrations.RunPython(create_change_requests_group, reverse_code=migrations.RunPython.noop),
    ]
