# Generated by Django 3.1.4 on 2021-04-29 10:15

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210428_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapikey',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='userapikey',
            unique_together={('user', 'site', 'name')},
        ),
    ]
