# Generated by Django 3.2.14 on 2022-08-07 10:25

from accounts.managers import UserManager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_auto_20220710_1746"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", UserManager()),
            ],
        ),
    ]
