# Generated by Django 3.1.4 on 2021-02-05 13:21

from django.db import migrations

from survey_designer.settings import INITIAL_ORGANIZATION


def _set_default_organization(apps, _):
    user_class = apps.get_model("accounts", "User")
    organization_class = apps.get_model("organization", "Organization")

    wfp_organization = organization_class.objects.get(name=INITIAL_ORGANIZATION)
    user_class.objects.update(organization=wfp_organization)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_organization'),
    ]

    operations = [
        migrations.RunPython(_set_default_organization, reverse_code=migrations.RunPython.noop),
    ]
