# Generated by Django 3.2.16 on 2023-03-23 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_assign_wfp_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAPISite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('api_type', models.CharField(choices=[('ONA', 'Ona'), ('KOBO', 'Kobo')], max_length=255)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('url', models.URLField()),
            ],
            options={
                'ordering': ['-date_created', '-date_updated'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='userapikey',
            name='temp_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_api_keys', to='accounts.userapisite'),
        ),
    ]
