# Generated by Django 3.2.16 on 2023-03-23 09:37

from django.db import migrations, models


class SiteType(models.TextChoices):
    MODA_DEV = "MODA_DEV", "MODA DEV"
    MODA = "MODA", "MODA"
    KOBO = "KOBO", "KOBO"

    @classmethod
    def get_base_url(cls, site):
        mapping = {
            cls.MODA_DEV: "https://api.dev.moda.wfp.org/",
            cls.MODA: "https://api.moda.wfp.org/",
            cls.KOBO: "https://kobo.humanitarianresponse.info/",
        }
        return mapping.get(site, "")


def create_user_api_sites(app, schema_editor):
    UserAPISite = app.get_model('accounts', 'UserAPISite')

    moda_dev = UserAPISite.objects.create(name='MODA DEV', api_type='ONA', url=SiteType.get_base_url(SiteType.MODA_DEV))
    moda = UserAPISite.objects.create(name='MODA', api_type='ONA', url=SiteType.get_base_url(SiteType.MODA))
    kobo = UserAPISite.objects.create(name='KOBO', api_type='KOBO', url=SiteType.get_base_url(SiteType.KOBO))

    UserAPIKey = app.get_model('accounts', "UserAPIKey")

    site_type_to_site_obj = {
        SiteType.MODA_DEV.value: moda_dev,
        SiteType.MODA.value: moda,
        SiteType.KOBO.value: kobo
    }

    for user_api_key in UserAPIKey.objects.all():
        try:
            new_site_obj = site_type_to_site_obj[user_api_key.site]
            user_api_key.temp_site = new_site_obj
            user_api_key.name = user_api_key.name or new_site_obj.name
            user_api_key.save()
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20230323_0934'),
    ]

    operations = [
        migrations.RunPython(create_user_api_sites, reverse_code=migrations.RunPython.noop),
    ]
