# Generated by Django 3.2.16 on 2023-03-23 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20230323_0937'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userapikey',
            unique_together={('user', 'temp_site', 'name')},
        ),
        migrations.RemoveField(
            model_name='userapikey',
            name='site',
        ),
    ]
