# Generated by Django 3.2.16 on 2023-03-23 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20230323_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userapikey',
            old_name='temp_site',
            new_name='site',
        ),
        migrations.AlterUniqueTogether(
            name='userapikey',
            unique_together={('user', 'site', 'name')},
        ),
    ]
