# Generated by Django 3.2.18 on 2023-05-17 11:12

from django.db import migrations, models


def _set_group_and_is_staff(apps, _):
    user_class = apps.get_model("accounts", "User")
    group_class = apps.get_model('auth', 'Group')

    for user in user_class.objects.filter(is_active=True, is_staff=False):
        user.is_staff = True
        group = group_class.objects.filter(name="Read Only").first()
        user.groups.add(group)
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_update_organization_users_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(_set_group_and_is_staff, reverse_code=migrations.RunPython.noop),
    ]
