name: 🛠️ Task / Chore
description: General improvements, maintenance, or internal tasks
title: "task: <title>"
labels: ["internal"]
body:
  - type: input
    id: parent-issue
    attributes:
      label: 📖 Parent User Story
      description: Enter the link or issue number of the Parent User Story (#123).
      placeholder: "#123"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Use this template for tasks that aren't bugs or features (e.g., refactoring, documentation, configuration, etc.).
        
        > [!IMPORTANT]
        > **Hierarchy Rules:**
        > - **Tasks** MUST have a **Parent User Story**.
        > - **Tasks** **cannot** have children and cannot have another Task or Feature as parent.

  - type: textarea
    id: description
    attributes:
      label: 🛠️ Task Description
      description: What needs to be done?
    validations:
      required: true

  - type: checkboxes
    id: software-layer
    attributes:
      label: 💻 Software layer
      description: What part is affected?
      options:
        - label: Front-end
        - label: Back-end

  - type: checkboxes
    id: todo
    attributes:
      label: 📋 To-do List
      options:
        - label: "Step 1"
        - label: "Step 2"
        - label: "Step 3"

  - type: textarea
    id: additional-context
    attributes:
      label: 📜 Additional Context
      description: Add any other context or screenshots here.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
