# Generated by Django 3.1.4 on 2021-02-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NestedSuffix',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Nested Suffixes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('questions.suffix',),
        ),
        migrations.RemoveField(
            model_name='suffix',
            name='related_suffixes',
        ),
        migrations.AddField(
            model_name='suffix',
            name='nested_suffixes',
            field=models.ManyToManyField(blank=True, related_name='parent_suffixes', to='questions.Suffix'),
        ),
    ]
