# Generated by Django 3.1.4 on 2021-02-09 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20210209_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubQuestionProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Sub Question',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('questions.subquestion',),
        ),
    ]
