# Generated by Django 3.1.4 on 2021-02-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_subquestionproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootquestion',
            name='constraint',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subquestion',
            name='constraint',
            field=models.TextField(blank=True),
        ),
    ]
