# Generated by Django 3.1.4 on 2021-02-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20210217_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootquestion',
            name='constraint_dependencies',
            field=models.ManyToManyField(blank=True, related_name='root_question_constraint_dependencies', to='questions.BaseQuestion'),
        ),
        migrations.AddField(
            model_name='rootquestion',
            name='constraint_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subquestion',
            name='constraint_dependencies',
            field=models.ManyToManyField(blank=True, related_name='sub_question_constraint_dependencies', to='questions.BaseQuestion'),
        ),
        migrations.AddField(
            model_name='subquestion',
            name='constraint_message',
            field=models.TextField(blank=True),
        ),
    ]
