# Generated by Django 3.1.4 on 2021-02-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20210223_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='subquestion',
            name='hint',
            field=models.TextField(blank=True, verbose_name='Hint (en)'),
        ),
        migrations.AddField(
            model_name='subquestiontranslation',
            name='hint',
            field=models.TextField(blank=True),
        ),
    ]
