# Generated by Django 3.1.4 on 2021-02-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20210224_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootquestion',
            name='relevant',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rootquestion',
            name='relevant_dependencies',
            field=models.ManyToManyField(blank=True, related_name='root_question_relevant_dependencies', to='questions.BaseQuestion'),
        ),
        migrations.AddField(
            model_name='subquestion',
            name='relevant',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subquestion',
            name='relevant_dependencies',
            field=models.ManyToManyField(blank=True, related_name='sub_question_relevant_dependencies', to='questions.BaseQuestion'),
        ),
    ]
