# Generated by Django 3.1.4 on 2021-02-25 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20210224_1340'),
    ]

    operations = [
        migrations.RenameModel('Indicator', 'Calculation')
    ]
