# Generated by Django 3.1.4 on 2021-02-25 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0009_auto_20210225_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_calculation_created_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='related_questions',
            field=models.ManyToManyField(blank=True, related_name='calculations', to='questions.BaseQuestion'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='submodule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='modules.submodule'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_calculation_updated_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
