# Generated by Django 3.1.4 on 2021-03-26 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_auto_20210225_0858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basequestion',
            options={'permissions': [('can_bulk_upload', 'Can bulk upload')], 'verbose_name': 'Question'},
        ),
    ]
