# Generated by Django 3.1.4 on 2021-03-30 15:51

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0002_auto_20210301_1108"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("questions", "0011_auto_20210326_1205"),
    ]

    operations = [
        migrations.CreateModel(
            name="RepeatSection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[core.validators.validate_wfp_name],
                        verbose_name="WFP Name",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("label", models.TextField(verbose_name="WFP Label (en)")),
                ("repeat_count", models.TextField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions_repeatsection_created_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "questions",
                    models.ManyToManyField(
                        related_name="repeat_sections", to="questions.BaseQuestion"
                    ),
                ),
                (
                    "repeat_count_dependencies",
                    models.ManyToManyField(
                        blank=True,
                        related_name="repeat_count_dependencies",
                        to="questions.BaseQuestion",
                    ),
                ),
                (
                    "submodule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repeat_sections",
                        to="modules.submodule",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions_repeatsection_updated_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
