# Generated by Django 3.1.4 on 2021-03-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_repeatsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='subquestion',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
