# Generated by Django 3.1.4 on 2021-04-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_subquestion_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootquestion',
            name='appearance',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subquestion',
            name='appearance',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
