# Generated by Django 3.1.4 on 2021-04-29 06:38

import core.validators
import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0014_auto_20210408_1049"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calculation",
            name="name",
            field=django.contrib.postgres.fields.citext.CICharField(
                max_length=255,
                unique=True,
                validators=[core.validators.validate_wfp_name],
                verbose_name="WFP Name",
            ),
        ),
        migrations.AlterField(
            model_name="choicegroup",
            name="name",
            field=django.contrib.postgres.fields.citext.CICharField(
                max_length=255,
                unique=True,
                validators=[core.validators.validate_wfp_name],
                verbose_name="WFP Name",
            ),
        ),
        migrations.AlterField(
            model_name="recallperiod",
            name="name",
            field=django.contrib.postgres.fields.citext.CICharField(
                max_length=255,
                unique=True,
                validators=[core.validators.validate_wfp_name],
                verbose_name="WFP Name",
            ),
        ),
        migrations.AlterField(
            model_name="repeatsection",
            name="name",
            field=django.contrib.postgres.fields.citext.CICharField(
                max_length=255,
                unique=True,
                validators=[core.validators.validate_wfp_name],
                verbose_name="WFP Name",
            ),
        ),
        migrations.AlterField(
            model_name="suffix",
            name="name",
            field=django.contrib.postgres.fields.citext.CICharField(
                max_length=255,
                unique=True,
                validators=[core.validators.validate_wfp_name],
                verbose_name="WFP Name",
            ),
        ),
    ]
