# Generated by Django 3.1.4 on 2021-04-29 09:57

import core.validators
import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0015_auto_20210429_0638"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rootquestion",
            name="name",
            field=django.contrib.postgres.fields.citext.CICharField(
                max_length=255,
                unique=True,
                validators=[core.validators.validate_wfp_name],
                verbose_name="WFP Name",
            ),
        ),
        migrations.AlterField(
            model_name="subquestion",
            name="name",
            field=django.contrib.postgres.fields.citext.CICharField(
                max_length=255,
                unique=True,
                validators=[core.validators.validate_wfp_name],
                verbose_name="WFP Name",
            ),
        ),
    ]
