# Generated by Django 3.1.4 on 2021-05-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_auto_20210429_0957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basequestion',
            options={'ordering': ('order',), 'permissions': [('can_bulk_upload', 'Can bulk upload')], 'verbose_name': 'Question'},
        ),
        migrations.AlterModelOptions(
            name='rootquestion',
            options={'ordering': ('base_question__order',), 'verbose_name': 'Root Question'},
        ),
        migrations.AlterModelOptions(
            name='subquestion',
            options={'ordering': ('base_question__order',), 'verbose_name': 'Question'},
        ),
        migrations.AddField(
            model_name='basequestion',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
