# Generated by Django 3.1.4 on 2021-05-12 12:18

from django.db import migrations


def reorder(apps, schema_editor):
    BaseQuestion = apps.get_model("questions", "BaseQuestion")
    for question in BaseQuestion.objects.all():
        question.order = question.id
        question.save()

class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_auto_20210512_1217'),
    ]

    operations = [
        migrations.RunPython(reorder, reverse_code=migrations.RunPython.noop),
    ]
