# Generated by Django 3.1.4 on 2021-05-12 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0018_auto_20210512_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basequestion',
            options={'ordering': ('-order',), 'permissions': [('can_bulk_upload', 'Can bulk upload')], 'verbose_name': 'Question'},
        ),
    ]
