# Generated by Django 3.1.4 on 2021-05-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0019_auto_20210512_1353'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='basequestion',
            index=models.Index(fields=['order'], name='questions_b_order_fa8edf_idx'),
        ),
        migrations.AddIndex(
            model_name='rootquestion',
            index=models.Index(fields=['type'], name='questions_r_type_8e5ab6_idx'),
        ),
        migrations.AddIndex(
            model_name='suffix',
            index=models.Index(fields=['type'], name='questions_s_type_47e614_idx'),
        ),
    ]
