# Generated by Django 3.1.4 on 2021-06-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0020_auto_20210512_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootquestion',
            name='type',
            field=models.CharField(choices=[('Aggregate', 'Aggregate'), ('calculate', 'calculate'), ('decimal', 'decimal'), ('geopoint', 'geopoint'), ('geotrace', 'geotrace'), ('geoshape', 'geoshape'), ('date', 'date'), ('time', 'time'), ('dateTime', 'dateTime'), ('integer', 'integer'), ('note', 'note'), ('same', 'same'), ('select_multiple', 'select_multiple'), ('select_one', 'select_one'), ('string', 'string'), ('text', 'text'), ('image', 'image'), ('audio', 'audio'), ('background-audio', 'background-audio'), ('video', 'video'), ('barcode', 'barcode'), ('acknowledge', 'acknowledge'), ('hidden', 'hidden')], max_length=255),
        ),
        migrations.AlterField(
            model_name='suffix',
            name='type',
            field=models.CharField(choices=[('Aggregate', 'Aggregate'), ('calculate', 'calculate'), ('decimal', 'decimal'), ('geopoint', 'geopoint'), ('geotrace', 'geotrace'), ('geoshape', 'geoshape'), ('date', 'date'), ('time', 'time'), ('dateTime', 'dateTime'), ('integer', 'integer'), ('note', 'note'), ('same', 'same'), ('select_multiple', 'select_multiple'), ('select_one', 'select_one'), ('string', 'string'), ('text', 'text'), ('image', 'image'), ('audio', 'audio'), ('background-audio', 'background-audio'), ('video', 'video'), ('barcode', 'barcode'), ('acknowledge', 'acknowledge'), ('hidden', 'hidden')], max_length=255),
        ),
    ]
