# Generated by Django 3.1.13 on 2021-12-08 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0023_auto_20210609_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='basequestion',
            name='repeat_section',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_question', to='questions.repeatsection'),
        ),
    ]
