# Generated by Django 3.1.13 on 2021-12-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0007_auto_20211125_1744'),
        ('questions', '0023_auto_20210609_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rootquestion',
            name='submodule',
        ),
        migrations.AddField(
            model_name='rootquestion',
            name='submodule',
            field=models.ManyToManyField(related_name='root_questions', to='modules.Submodule'),
        ),
    ]
