# Generated by Django 3.1.13 on 2021-12-08 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0024_basequestion_repeat_section'),
        ('questions', '0024_auto_20211205_2232'),
    ]

    operations = [
    ]
