# Generated by Django 3.1.13 on 2021-12-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0007_auto_20211125_1744'),
        ('questions', '0025_merge_20211208_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repeatsection',
            name='submodule',
        ),
        migrations.AddField(
            model_name='repeatsection',
            name='submodule',
            field=models.ManyToManyField(related_name='repeat_sections', to='modules.Submodule'),
        ),
    ]
