# Generated by Django 3.1.13 on 2021-12-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0026_auto_20211208_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='repeatsection',
            name='relevant',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='repeatsection',
            name='relevant_dependencies',
            field=models.ManyToManyField(blank=True, related_name='relevant_dependencies', to='questions.BaseQuestion'),
        ),
    ]
