# Generated by Django 3.1.13 on 2021-12-20 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0027_repeatsectiontranslation'),
        ('questions', '0027_auto_20211219_1239'),
    ]

    operations = [
    ]
