# Generated by Django 3.1.13 on 2021-12-21 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0029_auto_20211220_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choicegroup',
            options={'verbose_name': 'Choice list'},
        ),
    ]
