# Generated by Django 3.2.15 on 2022-08-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0032_auto_20220807_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootquestion',
            name='default',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rootquestion',
            name='disabled',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rootquestion',
            name='read_only',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rootquestion',
            name='required',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subquestion',
            name='default',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subquestion',
            name='disabled',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subquestion',
            name='read_only',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subquestion',
            name='required',
            field=models.TextField(blank=True),
        ),
    ]
