# Generated by Django 3.2.15 on 2022-09-20 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0033_auto_20220825_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculation',
            name='submodule',
        ),
        migrations.AddField(
            model_name='rootquestion',
            name='calculation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.calculation'),
        ),
    ]
