# Generated by Django 3.2.15 on 2022-09-23 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0034_auto_20220920_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootquestion',
            name='calculation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.calculation'),
        ),
    ]
