# Generated by Django 3.2.18 on 2023-05-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0035_alter_rootquestion_calculation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicetranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('ar', 'Arabic'), ('zh-cn', 'Chinese'), ('ru', 'Russian'), ('pt', 'Portuguese')], max_length=255),
        ),
        migrations.AlterField(
            model_name='repeatsectiontranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('ar', 'Arabic'), ('zh-cn', 'Chinese'), ('ru', 'Russian'), ('pt', 'Portuguese')], max_length=255),
        ),
        migrations.AlterField(
            model_name='rootquestionconstraintmessagetranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('ar', 'Arabic'), ('zh-cn', 'Chinese'), ('ru', 'Russian'), ('pt', 'Portuguese')], max_length=255),
        ),
        migrations.AlterField(
            model_name='rootquestiontranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('ar', 'Arabic'), ('zh-cn', 'Chinese'), ('ru', 'Russian'), ('pt', 'Portuguese')], max_length=255),
        ),
        migrations.AlterField(
            model_name='subquestionconstraintmessagetranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('ar', 'Arabic'), ('zh-cn', 'Chinese'), ('ru', 'Russian'), ('pt', 'Portuguese')], max_length=255),
        ),
        migrations.AlterField(
            model_name='subquestiontranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('ar', 'Arabic'), ('zh-cn', 'Chinese'), ('ru', 'Russian'), ('pt', 'Portuguese')], max_length=255),
        ),
    ]
