# Generated by Django 3.2.19 on 2023-06-26 14:23

import core.validators
import django.contrib.postgres.fields.citext
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0036_auto_20230518_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='label',
            field=models.TextField(verbose_name='Label (en)'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=255, unique=True, validators=[core.validators.validate_name], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='choicegroup',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=255, unique=True, validators=[core.validators.validate_name], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='recallperiod',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=255, unique=True, validators=[core.validators.validate_name], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='repeatsection',
            name='label',
            field=models.TextField(verbose_name='Label (en)'),
        ),
        migrations.AlterField(
            model_name='repeatsection',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=255, unique=True, validators=[core.validators.validate_name], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='rootquestion',
            name='label',
            field=models.TextField(verbose_name='Label (en)'),
        ),
        migrations.AlterField(
            model_name='rootquestion',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=255, unique=True, validators=[core.validators.validate_name], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='subquestion',
            name='label',
            field=models.TextField(verbose_name='Label (en)'),
        ),
        migrations.AlterField(
            model_name='subquestion',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=255, unique=True, validators=[core.validators.validate_name], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='suffix',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=255, unique=True, validators=[core.validators.validate_name], verbose_name='Name'),
        ),
    ]
