# Generated by Django 3.2.19 on 2023-07-17 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0037_auto_20230626_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_filter_name',
            field=models.ForeignKey(blank=True, help_text="Select a choice filter. Displayed as 'option_code': 'label' for the choice.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choice_filter_names', to='questions.choice'),
        ),
        migrations.AddField(
            model_name='choicegroup',
            name='choice_filter_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choice_filter_lists', to='questions.choicegroup'),
        ),
    ]
