# Generated by Django 3.2.19 on 2023-07-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0038_auto_20230717_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootquestion',
            name='choice_filter',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rootquestion',
            name='choice_filter_dependencies',
            field=models.ManyToManyField(blank=True, related_name='root_question_choice_filter_dependencies', to='questions.BaseQuestion'),
        ),
        migrations.AddField(
            model_name='subquestion',
            name='choice_filter',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subquestion',
            name='choice_filter_dependencies',
            field=models.ManyToManyField(blank=True, related_name='sub_question_choice_filter_dependencies', to='questions.BaseQuestion'),
        ),
    ]
