# Generated by Django 3.2.20 on 2023-07-26 15:54

from django.db import migrations, models


def migrate_calculations(apps, schema_editor):
    RootQuestion = apps.get_model('questions', 'RootQuestion')
    for question in RootQuestion.objects.all():
        if question.calculation:
            question.temp_calculation = question.calculation.calculation
            question.save()
            # Assign related_questions to calculation_dependencies
            question.calculation_dependencies.set(question.calculation.related_questions.all())


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0039_auto_20230717_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootquestion',
            name='calculation_dependencies',
            field=models.ManyToManyField(blank=True, related_name='root_question_calculation_dependencies', to='questions.BaseQuestion'),
        ),
        migrations.AddField(
            model_name='rootquestion',
            name='temp_calculation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subquestion',
            name='calculation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subquestion',
            name='calculation_dependencies',
            field=models.ManyToManyField(blank=True, related_name='sub_question_calculation_dependencies',
                                         to='questions.BaseQuestion'),
        ),
        migrations.RunPython(migrate_calculations, reverse_code=migrations.RunPython.noop),
    ]
