# Generated by Django 3.2.20 on 2023-07-31 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0040_calculation_text_field_refactor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rootquestion',
            name='calculation',
        ),
    ]
