# Generated by Django 3.2.20 on 2023-07-31 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0041_remove_rootquestion_calculation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rootquestion',
            old_name='temp_calculation',
            new_name='calculation',
        ),
    ]
