# Generated by Django 3.2.20 on 2023-09-13 16:14

from django.db import migrations
from django.db.models import Count


def clear_question_dependencies(model_name):
    def _clear_question_dependencies(apps, schema_editor):
        QuestionModel = apps.get_model("questions", model_name)

        constraint_affected_questions = QuestionModel.objects.annotate(
            num_constraints=Count("constraint_dependencies")
        ).filter(num_constraints__gt=0, constraint="")

        # Clear constraint_dependencies for each affected question
        for question in constraint_affected_questions:
            question.constraint_dependencies.clear()

        relevant_affected_questions = QuestionModel.objects.annotate(
            num_relevants=Count("relevant_dependencies")
        ).filter(num_relevants__gt=0, relevant="")

        # Clear relevant_dependencies for each affected question
        for question in relevant_affected_questions:
            question.relevant_dependencies.clear()

        choice_filter_affected_questions = QuestionModel.objects.annotate(
            num_choice_filters=Count("choice_filter_dependencies")
        ).filter(num_choice_filters__gt=0, choice_filter="")

        # Clear choice_filter_dependencies for each affected question
        for question in choice_filter_affected_questions:
            question.choice_filter_dependencies.clear()

        calculation_affected_questions = QuestionModel.objects.annotate(
            num_calculations=Count("calculation_dependencies")
        ).filter(num_calculations__gt=0, calculation="")

        # Clear calculation_dependencies for each affected question
        for question in calculation_affected_questions:
            question.calculation_dependencies.clear()
    return _clear_question_dependencies


def clear_repeat_section_dependencies(apps, schema_editor):
    RepeatSection = apps.get_model("questions", "RepeatSection")
    relevant_affected_repeat_sections = RepeatSection.objects.annotate(
        num_relevants=Count("relevant_dependencies")
    ).filter(num_relevants__gt=0, relevant="")

    # Clear relevant_dependencies for each affected repeat section
    for question in relevant_affected_repeat_sections:
        question.relevant_dependencies.clear()


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0042_rename_temp_calculation_rootquestion_calculation"),
    ]

    operations = [
        migrations.RunPython(
            clear_question_dependencies("RootQuestion"),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            clear_question_dependencies("SubQuestion"),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            clear_repeat_section_dependencies, reverse_code=migrations.RunPython.noop
        ),
    ]
