# Generated by Django 3.2.24 on 2024-05-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0043_clear_empty_dependencies_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
