# Generated by Django 4.2.20 on 2025-05-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0045_alter_calculation_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootquestion',
            name='parameters',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subquestion',
            name='parameters',
            field=models.TextField(blank=True),
        ),
    ]
