# Generated by Django 4.2.20 on 2025-05-16 13:40

from django.db import migrations, models


def populate_choice_order(apps, schema_editor):
    """
    For each ChoiceGroup:
      - Numeric names (e.g. "50") ordered by integer value
      - Then non-numeric names ordered lexicographically
    """
    Choice = apps.get_model("questions", "Choice")
    ChoiceGroup = apps.get_model("questions", "ChoiceGroup")

    # Import inside to keep migration import graph clean
    from django.db.models import Case, F, IntegerField, Value, When
    from django.db.models.expressions import OrderBy
    from django.db.models.functions import Cast

    for group in ChoiceGroup.objects.all().only("id"):
        qs = (
            Choice.objects.filter(choice_group=group)
            .annotate(
                # Cast purely-numeric names to INT; non-numeric -> NULL
                name_int=Case(
                    When(name__regex=r"^\d+$", then=Cast("name", IntegerField())),
                    default=Value(None),
                    output_field=IntegerField(),
                )
            )
            # NULLS LAST ensures non-numeric come after numeric
            .order_by(OrderBy(F("name_int"), nulls_last=True), "name", "id")
            .only("id")
        )

        for idx, choice in enumerate(qs, start=1):
            # Small, clear updates per row (keeps logic simple/safe)
            Choice.objects.filter(pk=choice.pk).update(order=idx)


def reset_order(apps, schema_editor):
    Choice = apps.get_model("questions", "Choice")
    Choice.objects.all().update(order=0)


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0046_rootquestion_parameters_subquestion_parameters"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterModelOptions(
            name="choice",
            options={
                "ordering": (
                    "order",
                    "id",
                )
            },
        ),
        migrations.RunPython(populate_choice_order, reset_order),
    ]
