# Generated by Django 4.2.23 on 2025-12-15 10:38

import core.validators
import django.contrib.postgres.fields.citext
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0047_choice_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootquestion',
            name='type',
            field=models.CharField(choices=[('Aggregate', 'Aggregate'), ('calculate', 'calculate'), ('decimal', 'decimal'), ('geopoint', 'geopoint'), ('geotrace', 'geotrace'), ('geoshape', 'geoshape'), ('date', 'date'), ('time', 'time'), ('dateTime', 'dateTime'), ('integer', 'integer'), ('note', 'note'), ('same', 'same'), ('select_multiple', 'select_multiple'), ('select_one', 'select_one'), ('select_one_from_file', 'select_one_from_file'), ('select_multiple_from_file', 'select_multiple_from_file'), ('rank', 'rank'), ('text', 'text'), ('image', 'image'), ('audio', 'audio'), ('background-audio', 'background-audio'), ('video', 'video'), ('barcode', 'barcode'), ('acknowledge', 'acknowledge'), ('hidden', 'hidden')], max_length=255),
        ),
        migrations.AlterField(
            model_name='suffix',
            name='type',
            field=models.CharField(choices=[('Aggregate', 'Aggregate'), ('calculate', 'calculate'), ('decimal', 'decimal'), ('geopoint', 'geopoint'), ('geotrace', 'geotrace'), ('geoshape', 'geoshape'), ('date', 'date'), ('time', 'time'), ('dateTime', 'dateTime'), ('integer', 'integer'), ('note', 'note'), ('same', 'same'), ('select_multiple', 'select_multiple'), ('select_one', 'select_one'), ('select_one_from_file', 'select_one_from_file'), ('select_multiple_from_file', 'select_multiple_from_file'), ('rank', 'rank'), ('text', 'text'), ('image', 'image'), ('audio', 'audio'), ('background-audio', 'background-audio'), ('video', 'video'), ('barcode', 'barcode'), ('acknowledge', 'acknowledge'), ('hidden', 'hidden')], max_length=255),
        ),
        migrations.CreateModel(
            name='ChoiceGroupFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', django.contrib.postgres.fields.citext.CICharField(max_length=255, unique=True, validators=[core.validators.validate_name], verbose_name='Name')),
                ('description', models.TextField(blank=True)),
                ('csv_file', models.FileField(upload_to='choice_lists/')),
                ('description_markdown', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Choice list with external file',
            },
        ),
        migrations.AddField(
            model_name='rootquestion',
            name='choices_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_questions', to='questions.choicegroupfile'),
        ),
        migrations.AddField(
            model_name='suffix',
            name='choices_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suffixes', to='questions.choicegroupfile'),
        ),
    ]
