# Generated by Django 5.2.11 on 2026-10-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0049_replace_citext_name_with_collation"),
    ]

    operations = [
        migrations.AddField(
            model_name="rootquestion",
            name="default_dependencies",
            field=models.ManyToManyField(
                blank=True,
                related_name="root_question_default_dependencies",
                to="questions.basequestion",
            ),
        ),
        migrations.AddField(
            model_name="rootquestion",
            name="read_only_dependencies",
            field=models.ManyToManyField(
                blank=True,
                related_name="root_question_read_only_dependencies",
                to="questions.basequestion",
            ),
        ),
        migrations.AddField(
            model_name="rootquestion",
            name="required_dependencies",
            field=models.ManyToManyField(
                blank=True,
                related_name="root_question_required_dependencies",
                to="questions.basequestion",
            ),
        ),
        migrations.AddField(
            model_name="subquestion",
            name="default_dependencies",
            field=models.ManyToManyField(
                blank=True,
                related_name="sub_question_default_dependencies",
                to="questions.basequestion",
            ),
        ),
        migrations.AddField(
            model_name="subquestion",
            name="read_only_dependencies",
            field=models.ManyToManyField(
                blank=True,
                related_name="sub_question_read_only_dependencies",
                to="questions.basequestion",
            ),
        ),
        migrations.AddField(
            model_name="subquestion",
            name="required_dependencies",
            field=models.ManyToManyField(
                blank=True,
                related_name="sub_question_required_dependencies",
                to="questions.basequestion",
            ),
        ),
    ]
