# Generated by Django 3.2.18 on 2023-03-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_add_global_admin_group'),
        ('change_requests', '0003_auto_20220710_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='organizations',
            field=models.ManyToManyField(to='organization.Organization'),
        ),
    ]
