# Generated by Django 4.2.17 on 2025-04-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_content', '0003_alter_frontendcontent_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontendcontent',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='frontendcontent',
            name='severity',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20),
        ),
    ]
