repos:
  - repo: local
    hooks:
      - id: frontend-tsc
        name: frontend-tsc
        entry: pnpm tsc
        language: system
        pass_filenames: false
      - id: frontend-lint
        name: frontend-lint
        entry: pnpm lint
        language: system
        pass_filenames: false
