# Generated by Django 3.1.13 on 2022-01-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
