# Generated by Django 3.1.4 on 2021-03-01 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmoduleMappingSurveyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mandatory', models.BooleanField(default=False)),
                ('submodule_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.submodulemapping')),
                ('survey_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.surveytype')),
            ],
            options={
                'unique_together': {('submodule_mapping', 'survey_type')},
            },
        ),
        migrations.CreateModel(
            name='SubmoduleMappingSurveyMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mandatory', models.BooleanField(default=False)),
                ('submodule_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.submodulemapping')),
                ('survey_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.surveymode')),
            ],
            options={
                'unique_together': {('submodule_mapping', 'survey_mode')},
            },
        ),
        migrations.CreateModel(
            name='SubmoduleMappingSurveyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mandatory', models.BooleanField(default=False)),
                ('submodule_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.submodulemapping')),
                ('survey_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.surveycategory')),
            ],
            options={
                'unique_together': {('submodule_mapping', 'survey_category')},
            },
        ),
        migrations.CreateModel(
            name='SubmoduleMappingSurveyAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mandatory', models.BooleanField(default=False)),
                ('submodule_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.submodulemapping')),
                ('survey_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyattribute')),
            ],
            options={
                'unique_together': {('submodule_mapping', 'survey_attribute')},
            },
        ),
        migrations.RemoveField(
            model_name='submodulemapping',
            name='survey_attributes',
        ),
        migrations.AddField(
            model_name='submodulemapping',
            name='survey_attributes',
            field=models.ManyToManyField(blank=True, related_name='submodule_mappings', through='modules.SubmoduleMappingSurveyAttribute', to='surveys.SurveyAttribute'),
        ),
        migrations.RemoveField(
            model_name='submodulemapping',
            name='survey_categories',
        ),
        migrations.AddField(
            model_name='submodulemapping',
            name='survey_categories',
            field=models.ManyToManyField(blank=True, related_name='submodule_mappings', through='modules.SubmoduleMappingSurveyCategory', to='surveys.SurveyCategory'),
        ),
        migrations.RemoveField(
            model_name='submodulemapping',
            name='survey_modes',
        ),
        migrations.AddField(
            model_name='submodulemapping',
            name='survey_modes',
            field=models.ManyToManyField(blank=True, related_name='submodule_mappings', through='modules.SubmoduleMappingSurveyMode', to='surveys.SurveyMode'),
        ),
        migrations.RemoveField(
            model_name='submodulemapping',
            name='survey_types',
        ),
        migrations.AddField(
            model_name='submodulemapping',
            name='survey_types',
            field=models.ManyToManyField(blank=True, related_name='submodule_mappings', through='modules.SubmoduleMappingSurveyType', to='surveys.SurveyType'),
        ),
    ]
