# Generated by Django 3.1.4 on 2021-04-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_auto_20210301_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='submodule',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
