# Generated by Django 3.1.4 on 2021-04-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_auto_20210406_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='submodule',
            name='appearance',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
