# Generated by Django 3.1.4 on 2021-04-23 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_submodule_appearance'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='default_submodule_mapping',
            field=models.OneToOneField(blank=True, help_text='This mapping will be used for newly created submodules.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module', to='modules.submodulemapping'),
        ),
    ]
