# Generated by Django 3.1.4 on 2021-04-29 06:38

import core.validators
import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0005_module_default_submodule_mapping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="name",
            field=django.contrib.postgres.fields.citext.CICharField(
                max_length=255,
                unique=True,
                validators=[core.validators.validate_wfp_name],
                verbose_name="WFP Name",
            ),
        ),
        migrations.AlterField(
            model_name="submodule",
            name="name",
            field=django.contrib.postgres.fields.citext.CICharField(
                max_length=255,
                unique=True,
                validators=[core.validators.validate_wfp_name],
                verbose_name="WFP Name",
            ),
        ),
    ]
