# Generated by Django 3.1.13 on 2021-11-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_auto_20210429_0638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='submodule',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submodule',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
