# Generated by Django 3.1.13 on 2021-12-13 02:22

import core.validators
import django.contrib.postgres.fields.citext
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0026_auto_20211208_0833"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("surveys", "0008_auto_20210429_0638"),
        ("modules", "0007_auto_20211125_1744"),
    ]

    operations = [
        migrations.CreateModel(
            name="Indicator",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "name",
                    django.contrib.postgres.fields.citext.CICharField(
                        max_length=255,
                        unique=True,
                        validators=[core.validators.validate_wfp_name],
                        verbose_name="WFP Name",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("label", models.TextField(verbose_name="WFP Label (en)")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modules_indicator_created_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "questions",
                    models.ManyToManyField(
                        related_name="indicators", to="questions.BaseQuestion"
                    ),
                ),
                (
                    "survey_types",
                    models.ManyToManyField(
                        related_name="indicators", to="surveys.SurveyType"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modules_indicator_updated_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
            },
        ),
    ]
