# Generated by Django 3.1.13 on 2021-12-14 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0026_auto_20211208_0833'),
        ('modules', '0008_indicator'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmoduleMappingRequiredGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_nested_suffix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_group_mappings_as_second', to='questions.suffix')),
                ('required_recall_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_group_mappings', to='questions.recallperiod')),
                ('required_suffix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_group_mappings', to='questions.suffix')),
                ('submodule_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_groups', to='modules.submodulemapping')),
            ],
            options={
                'unique_together': {('submodule_mapping', 'required_suffix', 'required_nested_suffix', 'required_recall_period')},
            },
        ),
    ]
