# Generated by Django 3.1.13 on 2021-12-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0026_auto_20211208_0833'),
        ('surveys', '0008_auto_20210429_0638'),
        ('modules', '0009_submodulemappingrequiredgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='indicators', to='questions.BaseQuestion'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='survey_types',
            field=models.ManyToManyField(blank=True, related_name='indicators', to='surveys.SurveyType'),
        ),
    ]
