# Generated by Django 3.1.13 on 2021-12-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0010_auto_20211215_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
