# Generated by Django 3.1.13 on 2021-12-20 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0011_auto_20211219_1334'),
        ('modules', '0011_indicator_url'),
    ]

    operations = [
    ]
