# Generated by Django 3.1.13 on 2021-12-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0029_auto_20211220_1440'),
        ('modules', '0012_merge_20211220_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submodule',
            name='relevant_dependencies',
            field=models.ManyToManyField(blank=True, related_name='submodule_relevant_dependencies', to='questions.BaseQuestion'),
        ),
    ]
