# Generated by Django 3.1.13 on 2022-01-05 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0030_auto_20211221_1039'),
        ('modules', '0013_auto_20211220_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmoduleRequiredGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_nested_suffix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_group_mappings_as_second', to='questions.suffix')),
                ('required_recall_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_group_mappings', to='questions.recallperiod')),
                ('required_suffix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_group_mappings', to='questions.suffix')),
                ('submodule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_groups', to='modules.submodule')),
            ],
            options={
                'unique_together': {('submodule', 'required_suffix', 'required_nested_suffix', 'required_recall_period')},
            },
        ),
        migrations.DeleteModel(
            name='SubmoduleMappingRequiredGroup',
        ),
    ]
