# Generated by Django 3.2.16 on 2022-12-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20221206_1316'),
        ('modules', '0016_auto_20220807_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='organizations',
            field=models.ManyToManyField(to='organization.Organization'),
        ),
    ]
