# Generated by Django 3.2.16 on 2023-01-17 12:16

import core.validators
import django.contrib.postgres.fields.citext
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modules', '0018_auto_20221222_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', django.contrib.postgres.fields.citext.CICharField(max_length=255, unique=True, validators=[core.validators.validate_wfp_name], verbose_name='WFP Name')),
                ('description', models.TextField(blank=True)),
                ('label', models.TextField(verbose_name='WFP Label (en)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('url', models.URLField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules_indicatorarea_created_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules_indicatorarea_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='indicator',
            name='indicator_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicators', to='modules.indicatorarea'),
        ),
    ]
