# Generated by Django 3.2.18 on 2023-05-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0019_indicator_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduletranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('ar', 'Arabic'), ('zh-cn', 'Chinese'), ('ru', 'Russian'), ('pt', 'Portuguese')], max_length=255),
        ),
        migrations.AlterField(
            model_name='submoduletranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('ar', 'Arabic'), ('zh-cn', 'Chinese'), ('ru', 'Russian'), ('pt', 'Portuguese')], max_length=255),
        ),
    ]
