# Generated by Django 3.2.19 on 2023-06-26 14:23

import core.validators
import django.contrib.postgres.fields.citext
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0020_auto_20230518_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='label',
            field=models.TextField(verbose_name='Label (en)'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=255, unique=True, validators=[core.validators.validate_name], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='indicatorarea',
            name='label',
            field=models.TextField(verbose_name='Label (en)'),
        ),
        migrations.AlterField(
            model_name='indicatorarea',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=255, unique=True, validators=[core.validators.validate_name], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='module',
            name='label',
            field=models.TextField(verbose_name='Label (en)'),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=255, unique=True, validators=[core.validators.validate_name], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='submodule',
            name='label',
            field=models.TextField(verbose_name='Label (en)'),
        ),
        migrations.AlterField(
            model_name='submodule',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=255, unique=True, validators=[core.validators.validate_name], verbose_name='Name'),
        ),
    ]
