# Generated by Django 3.2.22 on 2023-11-24 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def transfer_survey_types(apps, schema_editor):
    Indicator = apps.get_model('modules', 'Indicator')
    IndicatorMapping = apps.get_model('modules', 'IndicatorMapping')
    for indicator in Indicator.objects.all():
        if indicator.survey_types:
            mapping = IndicatorMapping.objects.create()
            mapping.survey_types.set(indicator.survey_types.all())
            indicator.mapping = mapping
            indicator.save()


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0018_auto_20230706_1312'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modules', '0021_auto_20230626_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules_indicatormapping_created_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),

        migrations.CreateModel(
            name='IndicatorMappingSurveyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mandatory', models.BooleanField(default=False)),
                ('indicator_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.indicatormapping')),
                ('survey_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.surveytype')),
            ],
            options={
                'unique_together': {('indicator_mapping', 'survey_type')},
            },
        ),
        migrations.AddField(
            model_name='indicatormapping',
            name='survey_types',
            field=models.ManyToManyField(blank=True, related_name='indicator_mappings', through='modules.IndicatorMappingSurveyType', to='surveys.SurveyType'),
        ),
        migrations.AddField(
            model_name='indicatormapping',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules_indicatormapping_updated_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indicator',
            name='mapping',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator', to='modules.indicatormapping'),
        ),
        migrations.RunPython(
            transfer_survey_types,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='survey_types',
        ),
    ]
