# Generated by Django 3.2.22 on 2024-01-08 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0018_auto_20230706_1312'),
        ('modules', '0022_auto_20231124_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorMappingSurveyMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mandatory', models.BooleanField(default=False)),
                ('indicator_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.indicatormapping')),
                ('survey_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.surveymode')),
            ],
            options={
                'unique_together': {('indicator_mapping', 'survey_mode')},
            },
        ),
        migrations.AddField(
            model_name='indicatormapping',
            name='survey_modes',
            field=models.ManyToManyField(blank=True, related_name='indicator_mappings', through='modules.IndicatorMappingSurveyMode', to='surveys.SurveyMode'),
        ),
    ]
