# Generated by Django 4.2.17 on 2025-03-03 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0019_alter_surveyattribute_created_by_and_more'),
        ('modules', '0027_alter_indicator_created_by_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indicatormappingsurveymode',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='indicatormappingsurveymode',
            name='survey_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modes', to='modules.indicatormappingsurveytype'),
        ),
        migrations.AlterUniqueTogether(
            name='indicatormappingsurveymode',
            unique_together={('indicator_mapping', 'survey_mode', 'survey_type')},
        ),
    ]
