# Generated by Django 4.2.17 on 2025-03-03 16:06
from django.db import migrations


def migrate_indicator_modes_to_types(apps, schema_editor):
    IndicatorMapping = apps.get_model("modules", "IndicatorMapping")
    IndicatorMappingSurveyMode = apps.get_model("modules", "IndicatorMappingSurveyMode")
    IndicatorMappingSurveyType = apps.get_model("modules", "IndicatorMappingSurveyType")

    for indicator_mapping in IndicatorMapping.objects.all():
        survey_types = IndicatorMappingSurveyType.objects.filter(
            indicator_mapping=indicator_mapping
        )
        survey_modes = IndicatorMappingSurveyMode.objects.filter(
            indicator_mapping=indicator_mapping
        )

        if survey_modes.exists() and survey_types.exists():
            first_type = survey_types.first()  # just the first type
            for mode in survey_modes:
                if not mode.survey_type:
                    mode.survey_type = first_type
                    mode.save()
            for survey_type in survey_types.exclude(pk=first_type.pk):
                for mode in survey_modes:
                    if not IndicatorMappingSurveyMode.objects.filter(
                        survey_type=survey_type,
                        survey_mode=mode.survey_mode,
                        indicator_mapping=indicator_mapping,
                    ).exists():
                        IndicatorMappingSurveyMode.objects.create(
                            indicator_mapping=indicator_mapping,
                            survey_type=survey_type,
                            survey_mode=mode.survey_mode,
                            is_mandatory=mode.is_mandatory,
                        )


def revert_indicator_modes_from_types(apps, schema_editor):
    IndicatorMapping = apps.get_model("modules", "IndicatorMapping")
    IndicatorMappingSurveyMode = apps.get_model("modules", "IndicatorMappingSurveyMode")
    IndicatorMappingSurveyType = apps.get_model("modules", "IndicatorMappingSurveyType")

    for indicator_mapping in IndicatorMapping.objects.all():
        survey_types = IndicatorMappingSurveyType.objects.filter(
            indicator_mapping=indicator_mapping
        ).order_by("id")
        if not survey_types.exists():
            continue

        first_type = survey_types.first()

        for extra_type in survey_types.exclude(pk=first_type.pk):
            IndicatorMappingSurveyMode.objects.filter(
                indicator_mapping=indicator_mapping, survey_type=extra_type
            ).delete()

        IndicatorMappingSurveyMode.objects.filter(
            indicator_mapping=indicator_mapping, survey_type=first_type
        ).update(survey_type=None)


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0019_alter_surveyattribute_created_by_and_more"),
        ("modules", "0028_alter_indicatormappingsurveymode_unique_together_and_more"),
    ]

    operations = [
        migrations.RunPython(
            migrate_indicator_modes_to_types,
            reverse_code=revert_indicator_modes_from_types,
        ),
    ]
