# Generated by Django 4.2.17 on 2025-03-03 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0019_alter_surveyattribute_created_by_and_more'),
        ('modules', '0029_migrate_indicatormapping_modes_to_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatormapping',
            name='survey_modes',
        ),
        migrations.AlterUniqueTogether(
            name='indicatormappingsurveymode',
            unique_together={('survey_mode', 'survey_type')},
        ),
        migrations.RemoveField(
            model_name='indicatormappingsurveymode',
            name='indicator_mapping',
        ),
    ]
