# Generated by Django 4.2.17 on 2025-03-05 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0019_alter_surveyattribute_created_by_and_more"),
        ("modules", "0030_remove_indicatormapping_survey_modes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndicatorMappingSurveyAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_mandatory", models.BooleanField(default=False)),
                (
                    "indicator_mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modules.indicatormapping",
                    ),
                ),
                (
                    "survey_attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="surveys.surveyattribute",
                    ),
                ),
            ],
            options={
                "unique_together": {("indicator_mapping", "survey_attribute")},
            },
        ),
        migrations.AddField(
            model_name="indicatormapping",
            name="survey_attributes",
            field=models.ManyToManyField(
                blank=True,
                related_name="indicator_mappings",
                through="modules.IndicatorMappingSurveyAttribute",
                to="surveys.surveyattribute",
            ),
        ),
    ]
