# Generated by Django 5.2.11 on 2026-04-01 12:33

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0032_replace_citext_name_with_collation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicatorarea",
            name="name",
            field=models.CharField(
                db_collation="case_insensitive",
                max_length=255,
                unique=True,
                validators=[core.validators.validate_name],
                verbose_name="Name",
            ),
        ),
    ]
