# Generated by Django 5.2.11 on 2026-04-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0033_alter_indicatorarea_name'),
        ('questions', '0049_replace_citext_name_with_collation'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='relevant',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='module',
            name='relevant_dependencies',
            field=models.ManyToManyField(blank=True, related_name='module_relevant_dependencies', to='questions.basequestion'),
        ),
    ]
