[tool.poetry]
name = "survey-designer"
version = "0.1.0"
description = ""
authors = ["Davis NDEGWAH <davis.ndegwah@wfp.org>"]

[tool.poetry.dependencies]
python = "^3.11"
Django = ">=5.2,<5.3"
gunicorn = "^23.0.0"
uvicorn = "^0.18.2"
django-health-check = "^3.16.5"
sentry-sdk = "2.8.0"
python-dotenv = "^0.20.0"
psycopg2-binary = "^2.9.3"
drf-spectacular = "^0.28.0"
django-cors-headers = "^4.3.0"
djangorestframework = "^3.16.0"
django-admin-autocomplete-filter = "^0.7.1"
django-dynamic-raw-id = "^4.3"
Authlib = "^1.3.1"
pandas = "^1.4.3"
python-docx = "^1.1.2"
requests = "2.32.4"
pyxform = "^1.10.1"
django-admin-sortable2 = "2.2.2"
django-rq = "^2.10.2"
django-nested-admin = "^3.4.0"
django-redis = "^5.2.0"
factory-boy = "^3.2.1"
django-pwa = "^1.0.10"
whitenoise = "^6.2.0"
django-storages = "^1.13.1"
boto3 = "^1.24.66"
django-extensions = "^3.2.1"
martor = "^1.6.16"
django-autocomplete-light = "^3.9.4"
django-filter = "^23.2"
django-silk = "^5.0.3"
sqlparse = ">=0.4.3"
redis = "4.5.4"
cryptography = "^44.0.3"
pytest-mock = "^3.11.1"
certifi = "2024.07.4"
django-minify-html = "1.6.1"
minify-html = "0.15.0"
urllib3 = "2.2.2"
idna = "3.7"
setuptools = "78.1.1"
zipp = "3.19.1"
rq = ">=1.14,<2.0.0"
openpyxl = "^3.0.9"
numpy = "1.25.2"

[tool.poetry.group.dev.dependencies]
black = "^24.3.0"
flake8 = "^4.0.1"
autoflake = "^1.4"
isort = "^5.10.1"
pytest-django = "^4.5.2"
pytest-cov = "^3.0.0"
pytest-xdist = "^3.0.2"
pre-commit = "^3.8.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
