# Generated by Django 3.2.19 on 2023-07-11 10:08

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saved_surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsurvey',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
