# Generated by Django 3.2.19 on 2023-07-11 12:26
import uuid

from django.db import migrations


def create_uuid(apps, schema_editor):
    SavedSurvey = apps.get_model("saved_surveys", "SavedSurvey")
    for saved_survey in SavedSurvey.objects.all():
        saved_survey.uuid = uuid.uuid4()
        saved_survey.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ('saved_surveys', '0002_alter_savedsurvey_id'),
    ]

    operations = [
        migrations.RunPython(create_uuid, reverse_code=migrations.RunPython.noop),
    ]
