# Generated by Django 3.2.19 on 2023-07-11 12:27
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saved_surveys', '0003_auto_20230711_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedsurvey',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
