# Generated by Django 3.2.22 on 2023-11-15 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0021_auto_20230626_1423'),
        ('saved_surveys', '0004_auto_20230711_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubModuleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('saved_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submodule_orders', to='saved_surveys.savedsurvey')),
                ('submodule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.submodule')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('saved_survey', 'submodule')},
            },
        ),
    ]
