# Generated by Django 3.2.24 on 2024-03-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saved_surveys', '0005_submoduleorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsurvey',
            name='languages',
            field=models.JSONField(blank=True, help_text='Select multiple languages', null=True),
        ),
    ]
